sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-011
env:
  global:
    -
      # LTD_AWS_ID
      secure: eKrw768RUE0fVulFdA4yJHFOIvG93qQefl6b8ivBRXxgueKhVVsqy8e27qBMw8RsDTcHQjSihMNGGmMI59gN+wU92D3VQYnB+fnBem8e2UkIXoNPBprBoRqx8sjqwlD6d52iSNAXyZ+fP7ngmeVm76XIwlb2XXtFTQYsfu4ohcsGaGQvCM6Se/2l1oExV5JQ3CW1RR+xIaTcGkPfozgnE1HT+HYzKUFywb/DXURvPqRm/wC0iEA7d9eFEl6/dZS2m0sc54mTvgv4tli3y69KSIVv9GxWfjg15ClMbEdlvoA5ijZZrO0bKx/HXlzW2k9WJta8qQAlBG0KV9dZ11CvLdM3DUGI4ciHoGfLothLCyIq/TGiTXZ3oCHmL8fVtss29nBDwEYbxBIu9t43JFZSrRSYMhdunWkD/0HmjGIqPntvnqWqfdpBVLqsTY1xHrnCI8I6LR4/rOYVz/eBQmDMQr0TfAdPfKN3PFBm1dAJwHJ6RiOFx+6GZgYs2YLapxvd1IMCeKmkvJmLDP96qT1UJNRS3lvgQotADn/3A8NxA1q2XVu80svTnmr7UzVTdpP9+IWlllZbykTQ8rAJzWX9rd6mKfyZ5e+feHeb9cf5yZ+kg3Wie1ZJGBMpdux9yQI5IwPeTIN+RucjDGDOfw7bdpjWQnFMagh+aFITB7BW0yg=
    -
      # LTD_AWS_SECRET
      secure: h5b2R04VTDoa3eRNvDZe4RAfm76NC6mJQEEBd9m/9Tutm4KTltr2uRhtr+4R2I2ALFPYFw/K8fargM1y++JZ0Hv13NI/cg6BDHL8sdbH8s76XMDqXuGxh4YbVuW/bGocq+5dR0xW1X69fBG9SP9SM5QcISOTyQgAgp8vzeAeJFeAp5k2JqbH5YwCkzIFWnWlU8HJWAyEIbJifL5zOhJ9Nq/2Vhry8LGddOMQro+xc9lh1CIdXzrW5Cx1Zvt/FHG6oD7q9TGRv3DxOY6YsjFllBwiAlZLuMlc8M6B+PZAJ9Qql0a5kJt8XBfLTLpIFmwmKr4SPS0tDFSJfLojTq6Yxl8xDSRrHp3LCCMiq6La3Qs+mZqW4yl4HbapA0dlxmMNYXFlvfyImVilff9RRNdw8HYyaFO32JkkDXwSicdvecdlDX/z83zW3qiFUBGwSDJegjULNofwG5rkz/JNwqAhpQg5eAvDrI81XHLzeyLvzG1WAmhlR9o4VDfEBt0J2ayZ9ZbGo2sFjvxouHMsYy/XhIHIpFnesO0I3ifSth2mpN/sD6epj/vv/8251pr1oQJulqdnU7iivuH+2Y62fF9id7wAr/aPF35gz8Ip/VNVtBNHfDmWpijuMcwEcCvXRMBnqDkZWUXV47rVxRLwVB3AW17dDooLThiNrS9ARHiIAJg=
    -
      # LTD_USERNAME
      secure: Jkb9ewUDYSMDpjojLvqH6o/Lbm1+qevmFlLfW+oqJCw0oZy9f51QdwTg/cmg+SJwPMwnGDMbAVTyOtEukbqIfGpU4FChJ0+P4dbJr+smSN0V3/J2QFsvw3G934d9DZg9NNzN1iPVmYnPtJUUJWCw3aEc/zpZr7RdhrW33fXQTnlKgh7C1MnKvdsC8LL0uBn/Z9S8pzrP/k7q9ZyiDbk+OKSfrr/EwoBs3ymKutMsotiPOW7rsRfN6h2K1NGzjHncfVB1UlL1b7GXXZQ0aLurba36hcPoa3UlH2YM0LYz6U6hqdrY9qE+W2QByqqFS7cV8bFNQWXzW4DgNm5UpS94MxrPDO+NNnryVzFoxD7vJNjPfMoeEaFInHInKGHdMmAwtFMa80oOxo3HtzeQ0eOtJTy/TsX/5ctjwy0BJOptEMMjKtjtSNhizyD4SRDBJYhNdl02wl4MPW1xDmv9zEV1blVVy4SHfTAKLsM4TzIYvB28rfVO0owIRUSz+tUZQLHS2SRRtS/gpEZNuPxB/4gYfw3PY2+j+uQOoxNjsFbZhIki+DZ/E9xsbg8Sdl83/eOXhkNFACpHT+3FGGJ9b51m4jxB95OKT5XZkBOWrCZysijmD0Y2wn2lsZYSrTUiYNcYoS90Zxa81qCMdJ3y9twSqMNzQDCKkx8m09T2pUJ3pEQ=
    -
      # LTD_PASSWORD
      secure: lgrzkysGhfZ7rlJzDVm+WstrV2Qj00nBkSbS1Rx5Jxx7Rd/uU96fcfK07fMWiq2C1jwyx1p2wboJJbkLZfvITyLNpzKhOoA5S/Kqv64HkHBrAOyXCnnK4IpSQDZcS/PpKVEn0JBoXhMILQ42Ru+eDUdZK37S2W3dA5cSHir07CcTLb9DLteKG09SqMzOVQm1mpMfmrYqCdOvaecM2W83ObGJBGhECpoHpjRlKtm6MMqy9T1DnvaLvMfGKu3jZtWacN9nrsGCxOzAn/Gnj7eRuzAHJwU41f3e85VhEb27d0w3PtQHjdCTd1bGymSlILVZSNbl3VaW+pK2Xa9/nnxaYv7/edK9+dpGFowLfSMAoN20Bq5eIV8DPtm1+k4NCL9aRvaBPhLngMrDkqFPYQeuEAeYXtVjC5X1zj92JU/Y/aouEvRmLRSXqNQxnfzuWbe2iF9f+zPHvEmUq2uQP005pFD+zHVRhKW9wiHruTfPJwbVbM1nJ1Vi4DPEhtaBdG/Y41ERQSFVdkz9gR8oZENCyG6j1koNBD6hBRUKmWMOQk5mZG1drMVFKmElJ7LU2wKbvJnpcf5BdfDi/1QF+PR/7Hpwq4/feq828Ut4THuSYNOldnegCxqriswcGNUHGGQAgPK28w6cD4hfnfR7+rI1XmD5kF8QTXyEZDfI4RtaU1s=
